name: Build and Deploy to Staging

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: hhacoffeeapics
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './CoffeeAPICs'
  DOTNET_VERSION: '3.1.407'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: 'Resolve Project Dependencies and Build'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Deploy Azure Function
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          slot-name: 'staging' # optional
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE_STAGING }}
